# Generated by Django 4.2.5 on 2023-09-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='polls',
            field=models.ManyToManyField(blank=True, to='voting_system.poll'),
        ),
    ]
