# Generated by Django 4.2.5 on 2023-09-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_system', '0002_alter_voter_polls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
