# Generated by Django 4.2.5 on 2023-09-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_system', '0003_alter_voter_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['-votes']},
        ),
    ]
